# Generated by Django 4.2.5 on 2023-10-07 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarTrips', '0002_planets_passengers_planets_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planets',
            old_name='safty',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='planets',
            name='traveltime',
        ),
        migrations.AlterField(
            model_name='planets',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planets',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
